AllCops:
  Include:
    - '**/*.gemspec'
    - '**/Rakefile'
  Exclude:
    - 'db/*'

LineLength:
  Description: 'Limit lines to 80 characters.'
  Max: 80

Documentation:
  Enabled: false

Encoding:
  Enabled: false

MethodLength:
  Description: 'Avoid methods longer than `Max` lines of code.'
  CountComments: false  # count full line comments?
  Max: 15

BlockLength:
  Enabled: false

AlignParameters:
  Enabled: false

ParameterLists:
  Description: 'Avoid parameter lists longer than five parameters.'
  Max: 5
  CountKeywordArgs: true

Semicolon:
  Description: "Don't use semicolons to terminate expressions."
  AllowAsExpressionSeparator: false

SingleLineMethods:
  Description: 'Avoid single-line methods.'
  AllowIfMethodIsEmpty: true

SpaceInsideHashLiteralBraces:
  Description: "Use spaces inside hash literal braces - or don't."
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space

BlockNesting:
  Description: 'Avoid more than `Max` levels of nesting.'
  Max: 4

# Align with the style guide.
CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

# Multi-line method chaining should be done with leading dots.
DotPosition:
  EnforcedStyle: leading

# TrivialAccessors doesn't require exact name matches and doesn't allow
# predicated methods by default.
TrivialAccessors:
  ExactNameMatch: false
  AllowPredicates: false
  Whitelist:
    - to_ary
    - to_a
    - to_c
    - to_enum
    - to_h
    - to_hash
    - to_i
    - to_int
    - to_io
    - to_open
    - to_path
    - to_proc
    - to_r
    - to_regexp
    - to_str
    - to_s
    - to_sym

# Allow safe assignment in conditions.
AssignmentInCondition:
  AllowSafeAssignment: true

# Allow safe assignment in conditions.
ParenthesesAroundCondition:
  AllowSafeAssignment: true

# Checks formatting of special comments
CommentAnnotation:
  Keywords:
    - TODO
    - FIXME
    - OPTIMIZE
    - HACK
    - REVIEW

Metrics/ClassLength:
  CountComments: false
  Max: 300

Style/AndOr:
    Enabled: false
