AddModelVirtualAttributeCheck: { }
AlwaysAddDbIndexCheck: { }
DefaultScopeIsEvilCheck: { }
DryBundlerInCapistranoCheck: { }
HashSyntaxCheck: { }
IsolateSeedDataCheck: { }
KeepFindersOnTheirOwnModelCheck: { }
MoveCodeIntoControllerCheck: { }
MoveCodeIntoHelperCheck: { array_count: 3 }
MoveCodeIntoModelCheck: { use_count: 2 }
MoveFinderToNamedScopeCheck: { }
MoveModelLogicIntoModelCheck: { use_count: 4 }
NeedlessDeepNestingCheck: { nested_count: 2 }
NotRescueExceptionCheck: { }
NotUseDefaultRouteCheck: { }
NotUseTimeAgoInWordsCheck: { }
OveruseRouteCustomizationsCheck: { customize_count: 3 }
ProtectMassAssignmentCheck: { }
RemoveEmptyHelpersCheck: { }
RemoveTrailingWhitespaceCheck: { }
RemoveUnusedMethodsInControllersCheck: {
  except_methods: [
    'ApplicationController#initialize',
    'ApplicationController#validate_type',
    'ApplicationController#validate_user',
    'ApplicationController#render_error',
    'Api::V1::UsersController#facebook_service_params',
    'Api::V1::UsersController#twitter_service_params',
    'Api::V1::UsersController#linked_in_service_params'
  ]
}
RemoveUnusedMethodsInHelpersCheck: { except_methods: [] }
RemoveUnusedMethodsInModelsCheck: { except_methods: [] }
ReplaceComplexCreationWithFactoryMethodCheck: { attribute_assignment_count: 2 }
ReplaceInstanceVariableWithLocalVariableCheck: { }
RestrictAutoGeneratedRoutesCheck: {
  ignored_files: [
    'routes\.rb' # false positives for explore entities
  ]
}
SimplifyRenderInControllersCheck: { }
SimplifyRenderInViewsCheck: { }
UseModelAssociationCheck: { }
UseObserverCheck: { }
UseQueryAttributeCheck: { }
UseSayWithTimeInMigrationsCheck: { }
UseScopeAccessCheck: {
  ignored_files: [
    'calculable\.rb'
  ]
}
UseTurboSprocketsRails3Check: { }
